# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-18 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MyChat', '0002_auto_20170218_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('title_img', models.ImageField(upload_to='uploads', verbose_name='\u6587\u7ae0\u56fe\u7247')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('publish_date', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('hidden', models.BooleanField(default=True, verbose_name='\u662f\u5426\u9690\u85cf')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyChat.UserProfile', verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u8bf4\u8bf4',
                'verbose_name_plural': '\u6587\u7ae0\u8bf4\u8bf4',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u7248\u5757\u540d\u5b57')),
                ('admin', models.ManyToManyField(to='MyChat.UserProfile', verbose_name='\u7ba1\u7406\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7248\u5757\u7c7b\u578b',
                'verbose_name_plural': '\u7248\u5757\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000, verbose_name='\u8bc4\u8bba')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyZone.Article', verbose_name='\u6587\u7ae0')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_comm', to='MyZone.Comment', verbose_name='\u4e0a\u7ea7\u8bc4\u8bba')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyChat.UserProfile', verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='ThumbUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyZone.Article', verbose_name='\u6587\u7ae0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyChat.UserProfile', verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u70b9\u8d5e',
                'verbose_name_plural': '\u70b9\u8d5e',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyZone.Category', verbose_name='\u7248\u5757\u7c7b\u578b'),
        ),
    ]
