# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-04 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyZone', '0002_auto_20170218_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, verbose_name='\u5185\u5bb9'),
        ),
    ]
