# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-04 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyZone', '0004_auto_20170304_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, default=1, verbose_name='\u5185\u5bb9'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title_img',
            field=models.ImageField(null=True, upload_to='uploads', verbose_name='\u6587\u7ae0\u56fe\u7247'),
        ),
    ]
