# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyZone', '0006_auto_20170304_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hidden',
        ),
    ]
