# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyChat', '0002_auto_20170218_1238'),
        ('MyZone', '0007_remove_article_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='admin',
        ),
        migrations.AddField(
            model_name='category',
            name='admin',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyChat.UserProfile', verbose_name='\u7ba1\u7406\u7528\u6237'),
            preserve_default=False,
        ),
    ]
