# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyZone', '0009_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u603b\u7ed3'),
        ),
    ]
