# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-18 01:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('brief', models.CharField(blank=True, max_length=255, null=True)),
                ('group_img', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('max_members', models.IntegerField(default=200)),
            ],
            options={
                'verbose_name': '\u7fa4\u7ec4',
                'verbose_name_plural': '\u7fa4\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('head_img', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('friends', models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to='MyChat.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='group_admins', to='MyChat.UserProfile'),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_members', to='MyChat.UserProfile'),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyChat.UserProfile'),
        ),
    ]
