# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-18 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyChat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='group_admins', to='MyChat.UserProfile', verbose_name='\u7fa4\u7ba1\u7406\u5458'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='brief',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='\u7fa4\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='max_members',
            field=models.IntegerField(default=200, verbose_name='\u6700\u5927\u6210\u5458'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_members', to='MyChat.UserProfile', verbose_name='\u7fa4\u6210\u5458'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(max_length=64, verbose_name='\u7fa4\u7ec4\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyChat.UserProfile', verbose_name='\u7fa4\u4e3b'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to='MyChat.UserProfile', verbose_name='\u670b\u53cb'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=32, verbose_name='\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7b7e\u540d'),
        ),
    ]
